### ISSUE TITLE
option to select LD reference

### ISSUE THREAD

**Issue by weinstockj** [statgen/localzoom#1]
Currently, there are no options to select the LD reference. Would be a great feature to choose from different LD sources. This could mean different 1KG populations or LD estimates from other studies. Text in the instructions state: 

> LD and overlay information is based on a specific build (build GRCh37 or build GRCh38 are supported). 

Would also be helpful to clarify what the default LD source is at the moment. 

Thanks for LocalZoom !

**Comment by abought** [comment]
Thanks for the suggestion! This feature is now available in released versions of LocalZoom and my.locuszoom.org. 

Eg: https://my.locuszoom.org/gwas/236887/region/?chrom=6&start=50636279&end=51036279

I've started gathering information about where data comes from, and will add it to the UI as part of #4 . Please let us know if there are any other improvements we can make for this or other features. :)
