### ISSUE TITLE
Use Build 38 GWAS with Build 37 PheWAS

### ISSUE THREAD

**Issue by weinstockj** [statgen/localzoom#2]
Currently, PheWAS lookups are only possible with build 37 GWAS results. Would be great to be able to convert coordinates between builds on the fly so that GWAS results and PheWAS results from different builds can be compared.

**Comment by abought** [comment]
A neat idea, but after giving some thought, I'll close this ticket for now.

My rationale is that by the time we would write a conversion, the old PheWAS we were comparing to would probably be pretty out of date, in which case it would make sense to "just" ingest a newer study with build 38 coordinates and more samples etc.
