### ISSUE TITLE
Are allele frequency columns auto-detected?

### ISSUE THREAD

**Issue by carbocation** [statgen/localzoom#26]
Related to #13 , I was eventually able to determine column names for P value, effect size, etc, that would be successfully parsed by looking at the [sniffers.js](https://github.com/statgen/locuszoom/blob/a271a0321339fb223721476244ece2fa7dec9820/esm/ext/lz-parsers/gwas/sniffers.js#L103) file. But I don't notice anything that automatically detects the allele frequency field. My field name (A1FREQ) is not being automatically parsed, but I don't know if there are any names that can be automatically parsed, or if allele frequency always requires a manual selection step. Any pointers?

**Comment by abought** [comment]
Good question, and glad it worked for you!

The short answer is that allele frequency always has to be manually specified. 

Longer answer: I'm actually quite in favor of automating it in theory, but in a very generic tool, this tends to be one of the more [pathological](https://github.com/statgen/locuszoom/blob/a271a0321339fb223721476244ece2fa7dec9820/esm/ext/lz-parsers/utils.js#L93-L122) fields to deal with- the "frequency or counts" mechanism relies on multiple other fields whose names are inconsistent across files, as well as subtle distinctions like "are your allele columns ref vs alt, major vs minor, or effect vs non-effect?".

In the end, we chose to omit "allele frequency" from the list of things we attempt to [guess](https://github.com/statgen/locuszoom/blob/a271a0321339fb223721476244ece2fa7dec9820/esm/ext/lz-parsers/gwas/sniffers.js#L228-L259).

I know this must sound pedantic, but some features we've explored adding, like value-added calculations, would have depended on knowing the correct meaning of data. We didn't want to build a tool whose calculations frequently produced nonsense, so we tried not to guess fields that would be highly ambiguous AND not easy to tell if we guessed wrong. 

Building an automated tool is always _so much easier_ with predictable data- this is one of those features that got cut in an attempt to be more generic. If you ever see a really reliable guesser routine, I'd be interested in seeing how they approach it!

**Comment by carbocation** [comment]
I guess my intuition was that even with manual intervention still being needed, the drop-down could still be pre-filled at a certain point. In the screenshot below, for example:

<img width="284" alt="image" src="https://user-images.githubusercontent.com/218804/207507022-5e092599-e2e7-4f0b-99f3-234e41f01823.png">

The Ref and Frequency radio buttons were manually selected, but it feels like once I've clicked on Frequency, it wouldn't be unreasonable to detect the frequency field. 

Navigating a dropdown is more painful than clicking on radio buttons, hence my interest in eliminating this final dropdown by naming my Frequency column in a way that will be detected after clicking on these radio buttons. 

(Of course, even if you accept my argument that it's reasonable to infer the frequency field after clicking on those radio buttons, that doesn't mean that it's worth spending dev time on something like this.)
