### ISSUE TITLE
Y-axis does not render correctly when Infinity -log10pvalue is present

### ISSUE THREAD

**Issue by weinstockj** [statgen/localzoom#6]
I have a variant with a pvalue of 0 due to precision limitations. As plotted in localzoom, I see:

![image](https://user-images.githubusercontent.com/7632297/76979089-e377ec00-690d-11ea-901f-3a2157921993.png)

The data row looks like this:

CHROM POS REF ALT BETA SEBETA TSTAT PVALUE
chr6  325357   G   A  -9.744225   0.816393 -11.935698  0.000000e+00

**Comment by abought** [comment]
Thanks for the bug report!

This is a known issue. Although I am closing this ticket to avoid duplication, it is an issue that we very much want to fix. See:
https://github.com/statgen/locuszoom/issues/141

The main reason for the delay is that doing so is not trivial (the code in question tries to do many things, and we want the fix to be reliable for all our various users). I'll try to keep you posted as options become available, even if it is not immediate.

Out of curiosity, what analysis program/version are you using? I've been a little surprised that new results are still subject to underflow errors. We had hoped that the problem would become less common as popular software improved, but clearly that hope was misplaced.

**Comment by weinstockj** [comment]
ok - thanks! I am using my own hand rolled program. I used scipy.stats to produce p-values, though not on log-scale. I'll switch to that.

**Comment by abought** [comment]
Good to know, thanks! 

Python is subject to this sort of underflow, but expressing things in log terms is an effective workaround. (our web app can parse small pvalues, like 10^-800, and convert to log if needed. But if the value is 0, there is not much that the parser can do)
